# Get editor completions based on the config schema
#"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# A minimal left prompt
format = """[‚ï≠‚ïº](bold purple) $username $sudo $os $hostname ‚õÅ $localip
[‚ï∞‚ïº ‚ï≠‚ïº](bold purple) $directory $shlvl $kubernetes $git_branch $jobs $git_status $aws $gcloud
[   ‚ï∞‚ïº](bold purple) $character"""

# move the rest of the prompt to the right
right_format = """$time$status"""

# Replace the '‚ùØ' symbol in the prompt
[character] # The name of the module we are configuring is 'character'
success_symbol = '[œü](bold green)' # The 'success_symbol' segment is being set to '‚ûú' with the color 'bold green'
error_symbol = "[‚ò¢](bold red) "

[localip]
disabled = false
format = '[\[$localipv4\]]($style)'
style = 'bold blue'
ssh_only = false

[shlvl]
disabled = false
format = '[\[ü™ú $shlvl\]]($style)'
threshold = 2

[directory]
format = ' [\[$path\]]($style)[$lock_symbol]($lock_style)[$read_only]($read_only_style)'
style = 'bold yellow'
truncation_length = 10 
truncate_to_repo = false

[battery]
full_symbol = "üîã"
charging_symbol = "üîå"
disabled = false
discharging_symbol = "‚ö°"

[hostname]
format = '[\[$hostname\]]($style)'
ssh_only = false
style = 'bold purple'
disabled = false

[status]
format = '[\[$symbol$status\]]($style)'
disabled = false
symbol = "[‚ò¢](bold red) "
not_executable_symbol = "[üö´](bold red) "
pipestatus = true


[aws]
format = '[\[$symbol($profile)(\($region\))(\[$duration\])\]]($style)'
disabled = true 

[bun]
format = '[\[$symbol($version)\]]($style)'

[c]
format = '[\[$symbol($version(-$name))\]]($style)'

[cmake]
format = '[\[$symbol($version)\]]($style)'

[cmd_duration]
format = '[\[‚è± $duration\]]($style)'
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)

[cobol]
format = '[\[$symbol($version)\]]($style)'

[conda]
format = '[\[$symbol$environment\]]($style)'

[crystal]
format = '[\[$symbol($version)\]]($style)'

[daml]
format = '[\[$symbol($version)\]]($style)'

[dart]
format = '[\[$symbol($version)\]]($style)'

[deno]
format = '[\[$symbol($version)\]]($style)'

[docker_context]
format = '[\[$symbol$context\]]($style)'

[dotnet]
format = '[\[$symbol($version)(üéØ $tfm)\]]($style)'

[elixir]
format = '[\[$symbol($version \(OTP $otp_version\))\]]($style)'

[elm]
format = '[\[$symbol($version)\]]($style)'

[erlang]
format = '[\[$symbol($version)\]]($style)'

[fennel]
format = '[\[$symbol($version)\]]($style)'

[fossil_branch]
format = '[\[$symbol$branch\]]($style)'

[gcloud]
format = '[\[$symbol$account(@$domain)(\($region\))\]]($style)'
disabled = true

[git_branch]
format = '[\[$symbol$branch\]]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '[\[$symbol($version)\]]($style)'

[gradle]
format = '[\[$symbol($version)\]]($style)'

[guix_shell]
format = '[\[$symbol\]]($style)'

[haskell]
format = '[\[$symbol($version)\]]($style)'

[haxe]
format = '[\[$symbol($version)\]]($style)'

[helm]
format = '[\[$symbol($version)\]]($style)'

[hg_branch]
format = '[\[$symbol$branch\]]($style)'

[java]
format = '[\[$symbol($version)\]]($style)'

[julia]
format = '[\[$symbol($version)\]]($style)'

[kotlin]
format = '[\[$symbol($version)\]]($style)'

[kubernetes]
format = '[\[$symbol$context( \($namespace\))\]]($style)'
disabled = false

[lua]
format = '[\[$symbol($version)\]]($style)'

[memory_usage]
format = '\[$symbol[$ram( | $swap)\]]($style)'
disabled = false

[meson]
format = '[\[$symbol$project\]]($style)'

[nim]
format = '[\[$symbol($version)\]]($style)'

[nix_shell]
format = '[\[$symbol$state( \($name\))\]]($style)'

[nodejs]
format = '[\[$symbol($version)\]]($style)'

[ocaml]
format = '[\[$symbol($version)(\($switch_indicator$switch_name\))\]]($style)'

[opa]
format = '[\[$symbol($version)\]]($style)'

[openstack]
format = '[\[$symbol$cloud(\($project\))\]]($style)'

[os]
format = '[$symbol]($style)'
disabled = false 

[os.symbols]
Manjaro = "üòà"

[package]
format = '[\[$symbol$version\]]($style)'
disabled = true

[perl]
format = '[\[$symbol($version)\]]($style)'

[php]
format = '[\[$symbol($version)\]]($style)'

[pijul_channel]
format = '[\[$symbol$channel\]]($style)'

[pulumi]
format = '[\[$symbol$stack\]]($style)'

[purescript]
format = '[\[$symbol($version)\]]($style)'

[python]
format = '[\[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))\]]($style)'

[raku]
format = '[\[$symbol($version-$vm_version)\]]($style)'

[red]
format = '[\[$symbol($version)\]]($style)'

[ruby]
format = '[\[$symbol($version)\]]($style)'

[rust]
format = '[\[$symbol($version)\]]($style)'

[scala]
format = '[\[$symbol($version)\]]($style)'

[spack]
format = '[\[$symbol$environment\]]($style)'

[sudo]
format = '[\[as $symbol\]]($style)'
symbol = '‚õ∫ '
disabled = false

[swift]
format = '[\[$symbol($version)\]]($style)'

[terraform]
format = '[\[$symbol$workspace\]]($style)'

[time]
format = '[\[$time\]]($style)'
time_format = "%F %T %Z"
style = "bold green"
disabled = false

[username]
format = '[\[$user\]]($style)'
style_user = 'green bold'
show_always = true

[vagrant]
format = '[\[$symbol($version)\]]($style)'

[vlang]
format = '[\[$symbol($version)\]]($style)'

[zig]
format = '[\[$symbol($version)\]]($style)'

[solidity]
format = '[\[$symbol($version)\]]($style)'

[jobs]
symbol = 'üíº'
format = '[\[$symbol$number\]]($style)'
